homebrew_taps:
  - caskroom/versions
  - simeji/jid
homebrew_cask_packages:
  - 1password
  - alfred
  - appcleaner
  - bettertouchtool
  - caffeine
  - clipmenu
  - dropbox
  - dash
  - gas-mask
  - google-chrome
  - google-japanese-ime
  - intellij-idea-ce
  - iterm2
  - jid
  - karabiner
  - kindle
  - remarshal
  - sequel-pro
  - skitch
  - skype
  - slack
  - sourcetree
  - sublime-text
  - vagrant
  - vagrant-manager
  - webstorm
