- name: install gvm
  shell: >
    (curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer) | bash
    creates=~/.gvm

- name: install nodebrew
  shell: >
    curl -L git.io/nodebrew | perl - setup
    creates=~/.nodebrew

- name: git clone dotfiles
  git: repo="{{ git.repo }}" dest="{{ git.dest }}"
  register: ret_clone

- name: copy dotfiles
  copy: src="{{ git.dest }}" dest=~
  register: ret_copy

- name: link dotfiles
  shell: >
    cd ~/dotfiles ; sh symlink.sh
  when: ret_copy|changed
